-- TMDB API 추가 필드: tagline, original_title, production_countries 등
ALTER TABLE movies
ADD COLUMN TAGLINE VARCHAR(500) COMMENT '짧은 한 줄 문구' AFTER TOP_REVIEW,
ADD COLUMN ORIGINAL_TITLE VARCHAR(500) COMMENT '원제' AFTER TAGLINE,
ADD COLUMN ORIGINAL_LANGUAGE VARCHAR(10) COMMENT '원어' AFTER ORIGINAL_TITLE,
ADD COLUMN PRODUCTION_COUNTRIES VARCHAR(255) COMMENT '제작국' AFTER ORIGINAL_LANGUAGE,
ADD COLUMN PRODUCTION_COMPANIES VARCHAR(500) COMMENT '제작사' AFTER PRODUCTION_COUNTRIES,
ADD COLUMN IMDB_ID VARCHAR(20) COMMENT 'IMDB ID' AFTER PRODUCTION_COMPANIES,
ADD COLUMN VOTE_COUNT INT COMMENT '평점 참여 인원' AFTER IMDB_ID;
