-- 알림 테이블 생성
CREATE TABLE IF NOT EXISTS notifications (
    NOTIFICATION_ID VARCHAR(255) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(255) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    MESSAGE VARCHAR(1000),
    NOTIFICATION_TYPE VARCHAR(50),
    RELATED_ID VARCHAR(255),
    IS_READ BOOLEAN DEFAULT FALSE,
    SENT_AT DATETIME,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255),
    MODIFIED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    MODIFIED_BY VARCHAR(255),
    INDEX idx_notifications_user_id (USER_ID),
    INDEX idx_notifications_is_read (IS_READ)
);
