-- 관리자 전용 로그인 (단독 테이블, 관계 없음)
CREATE TABLE IF NOT EXISTS `admin`
(
    ADMIN_ID     VARCHAR(255) NOT NULL COMMENT '관리자 ID (PK)',
    ADMIN_EMAIL  VARCHAR(255) NOT NULL COMMENT '이메일',
    PASSWORD     VARCHAR(255) NOT NULL COMMENT '비밀번호 (BCrypt 암호화)',
    ADMIN_NAME   VARCHAR(100) NOT NULL COMMENT '이름',
    ROLE         VARCHAR(50)  NOT NULL DEFAULT 'ADMIN' COMMENT '역할 (SUPER_ADMIN, ADMIN 등)',

    CREATED_AT   DATETIME     NOT NULL COMMENT '생성일자',
    CREATED_BY   VARCHAR(50)  NOT NULL COMMENT '생성자',
    MODIFIED_AT  DATETIME     NOT NULL COMMENT '수정일자',
    MODIFIED_BY  VARCHAR(50)  NOT NULL COMMENT '수정자',

    PRIMARY KEY (ADMIN_ID),
    UNIQUE KEY uk_admin_email (ADMIN_EMAIL)
);
