-- 탈퇴 회원 1년 보관: 소프트 삭제용 컬럼 추가
ALTER TABLE `users`
    ADD COLUMN STATUS      VARCHAR(20)  NULL DEFAULT 'ACTIVE' COMMENT '상태 (ACTIVE, WITHDRAWN, SUSPENDED)' AFTER PHONE,
    ADD COLUMN WITHDRAWN_AT DATETIME    NULL COMMENT '탈퇴 시점 (1년 후 물리 삭제 대상)' AFTER STATUS,
    ADD COLUMN LAST_LOGIN_AT DATETIME   NULL COMMENT '마지막 로그인 시각' AFTER WITHDRAWN_AT;
