CREATE TABLE dvd_stores (
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY,
    MANAGEMENT_NO   VARCHAR(50) NOT NULL,
    AREA_CODE       VARCHAR(20),
    BUSINESS_NAME   VARCHAR(200),
    STATUS_NAME     VARCHAR(30),
    STATUS_CODE     VARCHAR(5),
    ROAD_ADDRESS    VARCHAR(500),
    JIBUN_ADDRESS   VARCHAR(500),
    PHONE           VARCHAR(50),
    POSTAL_CODE     VARCHAR(10),
    LICENSE_DATE    VARCHAR(20),
    CLOSURE_DATE    VARCHAR(20),
    COORDINATE_X    VARCHAR(30),
    COORDINATE_Y    VARCHAR(30),
    PRODUCT_INFO    VARCHAR(500),
    FACILITY_AREA   VARCHAR(30),
    LAST_DATA_MODIFIED VARCHAR(30),
    CREATED_AT      DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UK_MANAGEMENT_NO (MANAGEMENT_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IDX_DVD_STORES_STATUS ON dvd_stores (STATUS_CODE);
CREATE INDEX IDX_DVD_STORES_NAME ON dvd_stores (BUSINESS_NAME);
CREATE INDEX IDX_DVD_STORES_AREA ON dvd_stores (AREA_CODE);
