TRUNCATE TABLE dvd_stores;

ALTER TABLE dvd_stores
    MODIFY COLUMN MANAGEMENT_NO VARCHAR(200) NOT NULL,
    MODIFY COLUMN AREA_CODE VARCHAR(50),
    MODIFY COLUMN BUSINESS_NAME VARCHAR(500),
    MODIFY COLUMN STATUS_NAME VARCHAR(50),
    MODIFY COLUMN STATUS_CODE VARCHAR(10),
    MODIFY COLUMN ROAD_ADDRESS TEXT,
    MODIFY COLUMN JIBUN_ADDRESS TEXT,
    MODIFY COLUMN PHONE VARCHAR(100),
    MODIFY COLUMN POSTAL_CODE VARCHAR(20),
    MODIFY COLUMN LICENSE_DATE VARCHAR(30),
    MODIFY COLUMN CLOSURE_DATE VARCHAR(30),
    MODIFY COLUMN COORDINATE_X VARCHAR(50),
    MODIFY COLUMN COORDINATE_Y VARCHAR(50),
    MODIFY COLUMN PRODUCT_INFO TEXT,
    MODIFY COLUMN FACILITY_AREA VARCHAR(50),
    MODIFY COLUMN LAST_DATA_MODIFIED VARCHAR(50);
