TRUNCATE TABLE dvd_stores;

ALTER TABLE dvd_stores MODIFY COLUMN BUSINESS_TYPE VARCHAR(500) NULL;
ALTER TABLE dvd_stores MODIFY COLUMN DETAIL_STATUS_NAME VARCHAR(200) NULL;
ALTER TABLE dvd_stores MODIFY COLUMN DETAIL_STATUS_CODE VARCHAR(50) NULL;
ALTER TABLE dvd_stores MODIFY COLUMN SUSPEND_START_DATE VARCHAR(100) NULL;
ALTER TABLE dvd_stores MODIFY COLUMN SUSPEND_END_DATE VARCHAR(100) NULL;
ALTER TABLE dvd_stores MODIFY COLUMN LICENSE_CANCEL_DATE VARCHAR(100) NULL;
ALTER TABLE dvd_stores MODIFY COLUMN DATA_UPDATE_DATE VARCHAR(100) NULL;
ALTER TABLE dvd_stores MODIFY COLUMN BUILDING_USAGE VARCHAR(500) NULL;
ALTER TABLE dvd_stores MODIFY COLUMN FLOOR_ABOVE VARCHAR(50) NULL;
ALTER TABLE dvd_stores MODIFY COLUMN FLOOR_BELOW VARCHAR(50) NULL;
ALTER TABLE dvd_stores MODIFY COLUMN FLOOR_TOTAL VARCHAR(50) NULL;
ALTER TABLE dvd_stores MODIFY COLUMN REGION_TYPE VARCHAR(200) NULL;
ALTER TABLE dvd_stores MODIFY COLUMN GAME_NAME TEXT NULL;
ALTER TABLE dvd_stores MODIFY COLUMN SURROUNDING_ENV TEXT NULL;

ALTER TABLE dvd_stores ADD COLUMN DATA_UPDATE_TYPE VARCHAR(20) NULL;
ALTER TABLE dvd_stores ADD COLUMN PREV_GAME_BIZ_TYPE VARCHAR(500) NULL;
ALTER TABLE dvd_stores ADD COLUMN CULTURAL_BIZ_TYPE VARCHAR(200) NULL;
