ALTER TABLE dvd_stores ADD COLUMN DATA_UPDATE_TYPE VARCHAR(20) NULL;
ALTER TABLE dvd_stores ADD COLUMN PREV_GAME_BIZ_TYPE VARCHAR(500) NULL;
ALTER TABLE dvd_stores ADD COLUMN CULTURAL_BIZ_TYPE VARCHAR(200) NULL;
