CREATE TABLE movie_reviews (
    REVIEW_ID    VARCHAR(255) NOT NULL,
    USER_ID      VARCHAR(255) NOT NULL,
    MOVIE_NAME   VARCHAR(500) NOT NULL,
    CONTENT_TYPE VARCHAR(20)  DEFAULT 'movie',
    ONE_LINER    VARCHAR(500),
    FULL_REVIEW  TEXT,
    IS_SPOILER   TINYINT(1)   DEFAULT 0,
    CREATED_AT   DATETIME     DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY   VARCHAR(255),
    MODIFIED_AT  DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    MODIFIED_BY  VARCHAR(255),
    PRIMARY KEY (REVIEW_ID),
    INDEX idx_movie_reviews_movie (MOVIE_NAME, CONTENT_TYPE),
    INDEX idx_movie_reviews_user  (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
