ALTER TABLE movies ADD COLUMN MOVIE_NAME_EN VARCHAR(500);
ALTER TABLE movies ADD COLUMN OVERVIEW_EN TEXT;
ALTER TABLE movies ADD COLUMN TAGLINE_EN VARCHAR(500);
ALTER TABLE movies ADD COLUMN POSTER_PATH_EN VARCHAR(500);
ALTER TABLE movies ADD COLUMN BACKDROP_PATH_EN VARCHAR(500);
